# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mxnfEuX9HbTnKC-gj6U8d3Z8V6b0Q4-U
"""

import requests
import json

url1 = ('http://api.openweathermap.org/data/2.5/weather?'
         'lat=63.16&'
         'lon=75.29&'
         'appid=7cdcfaa69a322e2c77fdf3043de45290&'
         'units=metric&'
         'lang=ru')
r1 = requests.get(url1)
r1 = r1.json()
print("погода в Ноябрьске:", r1['weather'][0]['description'])
print("температура:", r1['main']['temp'], "по Цельсию")
print("давление:", r1['main']['pressure'], "гекто-паскаль")
print("влажность:", r1['main']['humidity'], "%")
with open('requests1.json', 'w') as file_1:
    json.dump(r1, file_1, indent=3)

url2 = ('https://api.hh.ru/employers?'
         'text=Python&'
         'locale=RU&'
         'host=hh.ru'
         )

r2 = requests.get(url2)
r2 = r2.json()
with open('requests2.json', 'w') as file_2:
    json.dump(r2, file_2, indent=3)


url3 = ('https://rest.coinapi.io/v1/exchangerate/ETH/RUB')
headers = {"X-CoinAPI-Key" : "17DF23BD-FEAB-44FF-AB86-3582CAF5422D"}
r3 = requests.get(url3, headers = headers)
r3 = r3.json()
with open('requests3.json', 'w') as file_3:
    json.dump(r3, file_3, indent=3)